[[ics]]
# XjMCS - XTjr Memory Chip Selection logic v1 XGPro IC Test Definition
# To be used with https://github.com/evolutional/xgpro-logic to convert to .lgc file for testing on xgpro software
name = "XjMCSv1a"
pins = 20
vcc = 5
vectors = [
	"X000000XXG0HLXXXXXXV",
	"X100000XXG0HLXXXXXXV",
	"X010000XXG0HLXXXXXXV",
	"X110000XXG0HLXXXXXXV",
	"X001000XXG0HLXXXXXXV",
	"X101000XXG0HLXXXXXXV",
	"X011000XXG0HLXXXXXXV",
	"X111000XXG0HLXXXXXXV",
	"X000100XXG0HLXXXXXXV",
	"X100100XXG0HLXXXXXXV",
	"X010100XXG0HLXXXXXXV",
	"X110100XXG0HLXXXXXXV",
	"X001100XXG0HLXXXXXXV",
	"X101100XXG0HLXXXXXXV",
	"X011100XXG0HLXXXXXXV",
	"X111100XXG0HLXXXXXXV",
	"X000010XXG0HLXXXXXXV",
	"X100010XXG0HLXXXXXXV",
	"X010010XXG0HLXXXXXXV",
	"X110010XXG0HLXXXXXXV",
	"X001010XXG0HHXXXXXXV",
	"X101010XXG0HHXXXXXXV",
	"X011010XXG0HHXXXXXXV",
	"X111010XXG0HHXXXXXXV",
	"X000110XXG0HHXXXXXXV",
	"X100110XXG0HHXXXXXXV",
	"X010110XXG0HHXXXXXXV",
	"X110110XXG0HHXXXXXXV",
	"X001110XXG0HLXXXXXXV",
	"X101110XXG0HLXXXXXXV",
	"X011110XXG0LHXXXXXXV",
	"X111110XXG0LHXXXXXXV",
	"X000001XXG0HHXXXXXXV",
	"X100001XXG0HHXXXXXXV",
	"X010001XXG0HHXXXXXXV",
	"X110001XXG0HHXXXXXXV",
	"X001001XXG0HHXXXXXXV",
	"X101001XXG0HHXXXXXXV",
	"X011001XXG0HHXXXXXXV",
	"X111001XXG0HHXXXXXXV",
	"X000101XXG0HHXXXXXXV",
	"X100101XXG0HHXXXXXXV",
	"X010101XXG0HHXXXXXXV",
	"X110101XXG0HHXXXXXXV",
	"X001101XXG0HHXXXXXXV",
	"X101101XXG0HHXXXXXXV",
	"X011101XXG0HHXXXXXXV",
	"X111101XXG0HHXXXXXXV",
	"X000011XXG0HHXXXXXXV",
	"X100011XXG0HHXXXXXXV",
	"X010011XXG0HHXXXXXXV",
	"X110011XXG0HHXXXXXXV",
	"X001011XXG0HHXXXXXXV",
	"X101011XXG0HHXXXXXXV",
	"X011011XXG0HHXXXXXXV",
	"X111011XXG0HHXXXXXXV",
	"X000111XXG0HHXXXXXXV",
	"X100111XXG0HHXXXXXXV",
	"X010111XXG0HHXXXXXXV",
	"X110111XXG0HHXXXXXXV",
	"X001111XXG0HHXXXXXXV",
	"X101111XXG0HHXXXXXXV",
	"X011111XXG0HHXXXXXXV",
	"X111111XXG0HHXXXXXXV",
	"X000000XXG1HLXXXXXXV",
	"X100000XXG1HLXXXXXXV",
	"X010000XXG1HLXXXXXXV",
	"X110000XXG1HLXXXXXXV",
	"X001000XXG1HLXXXXXXV",
	"X101000XXG1HLXXXXXXV",
	"X011000XXG1HLXXXXXXV",
	"X111000XXG1HLXXXXXXV",
	"X000100XXG1HLXXXXXXV",
	"X100100XXG1HLXXXXXXV",
	"X010100XXG1HLXXXXXXV",
	"X110100XXG1HLXXXXXXV",
	"X001100XXG1HLXXXXXXV",
	"X101100XXG1HLXXXXXXV",
	"X011100XXG1HLXXXXXXV",
	"X111100XXG1HLXXXXXXV",
	"X000010XXG1HLXXXXXXV",
	"X100010XXG1HLXXXXXXV",
	"X010010XXG1HLXXXXXXV",
	"X110010XXG1HLXXXXXXV",
	"X001010XXG1HHXXXXXXV",
	"X101010XXG1HHXXXXXXV",
	"X011010XXG1HHXXXXXXV",
	"X111010XXG1HHXXXXXXV",
	"X000110XXG1HHXXXXXXV",
	"X100110XXG1HHXXXXXXV",
	"X010110XXG1HHXXXXXXV",
	"X110110XXG1HHXXXXXXV",
	"X001110XXG1LHXXXXXXV",
	"X101110XXG1LHXXXXXXV",
	"X011110XXG1LHXXXXXXV",
	"X111110XXG1LHXXXXXXV",
	"X000001XXG1HHXXXXXXV",
	"X100001XXG1HHXXXXXXV",
	"X010001XXG1HHXXXXXXV",
	"X110001XXG1HHXXXXXXV",
	"X001001XXG1HHXXXXXXV",
	"X101001XXG1HHXXXXXXV",
	"X011001XXG1HHXXXXXXV",
	"X111001XXG1HHXXXXXXV",
	"X000101XXG1HHXXXXXXV",
	"X100101XXG1HHXXXXXXV",
	"X010101XXG1HHXXXXXXV",
	"X110101XXG1HHXXXXXXV",
	"X001101XXG1HHXXXXXXV",
	"X101101XXG1HHXXXXXXV",
	"X011101XXG1HHXXXXXXV",
	"X111101XXG1HHXXXXXXV",
	"X000011XXG1HHXXXXXXV",
	"X100011XXG1HHXXXXXXV",
	"X010011XXG1HHXXXXXXV",
	"X110011XXG1HHXXXXXXV",
	"X001011XXG1HHXXXXXXV",
	"X101011XXG1HHXXXXXXV",
	"X011011XXG1HHXXXXXXV",
	"X111011XXG1HHXXXXXXV",
	"X000111XXG1HHXXXXXXV",
	"X100111XXG1HHXXXXXXV",
	"X010111XXG1HHXXXXXXV",
	"X110111XXG1HHXXXXXXV",
	"X001111XXG1HHXXXXXXV",
	"X101111XXG1HHXXXXXXV",
	"X011111XXG1HHXXXXXXV",
	"X111111XXG1HHXXXXXXV",
	"XXXXXX000GXXXXXLLHHV",
	"XXXXXX001GXXXXXLHHHV",
	"XXXXXX010GXXXXXHLHHV",
	"XXXXXX011GXXXXXHHHHV",
	"XXXXXX100GXXXXXHHLLV",
	"XXXXXX101GXXXXXHHLHV",
	"XXXXXX110GXXXXXHHHLV",
	"XXXXXX111GXXXXXHHHHV",
	"0XXXXX000GXXXHHXXXXV",
	"0XXXXX001GXXXHHXXXXV",
	"0XXXXX010GXXXHHXXXXV",
	"0XXXXX011GXXXHHXXXXV",
	"0XXXXX100GXXXLLXXXXV",
	"0XXXXX101GXXXLHXXXXV",
	"0XXXXX110GXXXHLXXXXV",
	"0XXXXX111GXXXHHXXXXV",
	"1XXXXX000GXXXHHXXXXV",
	"1XXXXX001GXXXHHXXXXV",
	"1XXXXX010GXXXHHXXXXV",
	"1XXXXX011GXXXHHXXXXV",
	"1XXXXX100GXXXHHXXXXV",
	"1XXXXX101GXXXHHXXXXV",
	"1XXXXX110GXXXHHXXXXV",
	"1XXXXX111GXXXHHXXXXV"
]
